/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ErrantTowerServer
 * OpenAPI spec version: 1.0
 */

export interface CompleteSignInRequest {
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 6
   * @maxLength 6
   */
  actionCode: string;
}
