/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ErrantTowerServer
 * OpenAPI spec version: 1.0
 */

export interface GetCurrentUserResponse {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  email: string;
}
