/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ErrantTowerServer
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompleteSignInRequest,
  CompleteSignInResponse,
  CompleteSignUpRequest,
  CompleteSignUpResponse,
  GetCurrentUserResponse,
  StartSignInRequest,
  StartSignUpRequest
} from './definitions';

import { customFetch } from './custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const startSignUp = (
    startSignUpRequest: StartSignUpRequest,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/users/sign-up/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startSignUpRequest, signal
    },
      options);
    }
  


export const getStartSignUpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startSignUp>>, TError,{data: StartSignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startSignUp>>, TError,{data: StartSignUpRequest}, TContext> => {

const mutationKey = ['startSignUp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startSignUp>>, {data: StartSignUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  startSignUp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof startSignUp>>>
    export type StartSignUpMutationBody = StartSignUpRequest
    export type StartSignUpMutationError = unknown

    export const useStartSignUp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startSignUp>>, TError,{data: StartSignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startSignUp>>,
        TError,
        {data: StartSignUpRequest},
        TContext
      > => {

      const mutationOptions = getStartSignUpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const completeSignUp = (
    completeSignUpRequest: CompleteSignUpRequest,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<CompleteSignUpResponse>(
      {url: `/users/sign-up/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeSignUpRequest, signal
    },
      options);
    }
  


export const getCompleteSignUpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSignUp>>, TError,{data: CompleteSignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeSignUp>>, TError,{data: CompleteSignUpRequest}, TContext> => {

const mutationKey = ['completeSignUp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeSignUp>>, {data: CompleteSignUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  completeSignUp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof completeSignUp>>>
    export type CompleteSignUpMutationBody = CompleteSignUpRequest
    export type CompleteSignUpMutationError = unknown

    export const useCompleteSignUp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSignUp>>, TError,{data: CompleteSignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeSignUp>>,
        TError,
        {data: CompleteSignUpRequest},
        TContext
      > => {

      const mutationOptions = getCompleteSignUpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const startSignIn = (
    startSignInRequest: StartSignInRequest,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/users/sign-in/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startSignInRequest, signal
    },
      options);
    }
  


export const getStartSignInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startSignIn>>, TError,{data: StartSignInRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startSignIn>>, TError,{data: StartSignInRequest}, TContext> => {

const mutationKey = ['startSignIn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startSignIn>>, {data: StartSignInRequest}> = (props) => {
          const {data} = props ?? {};

          return  startSignIn(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartSignInMutationResult = NonNullable<Awaited<ReturnType<typeof startSignIn>>>
    export type StartSignInMutationBody = StartSignInRequest
    export type StartSignInMutationError = unknown

    export const useStartSignIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startSignIn>>, TError,{data: StartSignInRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startSignIn>>,
        TError,
        {data: StartSignInRequest},
        TContext
      > => {

      const mutationOptions = getStartSignInMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const completeSignIn = (
    completeSignInRequest: CompleteSignInRequest,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<CompleteSignInResponse>(
      {url: `/users/sign-in/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeSignInRequest, signal
    },
      options);
    }
  


export const getCompleteSignInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSignIn>>, TError,{data: CompleteSignInRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeSignIn>>, TError,{data: CompleteSignInRequest}, TContext> => {

const mutationKey = ['completeSignIn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeSignIn>>, {data: CompleteSignInRequest}> = (props) => {
          const {data} = props ?? {};

          return  completeSignIn(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteSignInMutationResult = NonNullable<Awaited<ReturnType<typeof completeSignIn>>>
    export type CompleteSignInMutationBody = CompleteSignInRequest
    export type CompleteSignInMutationError = unknown

    export const useCompleteSignIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSignIn>>, TError,{data: CompleteSignInRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeSignIn>>,
        TError,
        {data: CompleteSignInRequest},
        TContext
      > => {

      const mutationOptions = getCompleteSignInMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getCurrentUser = (
    
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GetCurrentUserResponse>(
      {url: `/users/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCurrentUserQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = unknown


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





